apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque
data:
  sql-user: c3FsdXNlcg==
  sql-password: c3FscGFzcw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config
data:
  sql-url: sql-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sqldb
        image: postgres:16.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
               name: sql-secret
               key: sql-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
               name: sql-secret
               key: sql-password
---
apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
