---
- name: Check kernel version on Linux VM
  hosts: "{{ target_host }}"
  gather_facts: no
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
  tasks:
    - name: Check the kernel version
      ansible.builtin.shell: uname -r
      register: kernel_version

    - name: Export outputs
      torque.collections.export_torque_outputs:
        outputs:
          output1: "{{ kernel_version }}"
