---
- name: Check kernel version on Linux VM
  hosts: localhost
  gather_facts: no
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
  tasks:
    - name: Check the kernel version
      delegate_to: "{{ target_host }}"
      ansible.builtin.shell: uname -r
      register: kernel_version
    
    - name: Display kernel version
      debug:
        msg: "The kernel version is {{ kernel_version.stdout }}"

    - name: Export outputs
      torque.collections.export_torque_outputs:
        outputs:
          output1: "{{ kernel_version }}"
