---
- hosts: '{{ nodes }}'  # This targets all machines in your inventory
  become: true  # Allows tasks to run with elevated privileges
  tasks:
    - name: Configure virtual machine
      username: "{{ username }}"
      password: "{{ password }}"

    - name: Update package cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Apache2 package
      apt: 
        name: apache2
        state: present

    - name: Create a simple index.html file (optional)
      copy:
        content: "<html><h1>Welcome to your Ansible-provisioned Apache server!</h1></html>"
        dest: /var/www/html/index.html
        mode: 0644

    - name: Enable and start Apache service
      service:
        name: apache2
        enabled: yes
        state: started
